name: MinewestCore
main: net.minewest.minewestcore.MinewestCorePlugin
author: Taon2
version: 1.0.3
commands:
  sleep:
    description: Accepts or denies a request to sleep.
    usage: /sleep {accept/deny}
