name: MinewestCore
main: net.minewest.minewestcore.MinewestCorePlugin
authors: [Taon2, spencrr]
version: 1.0.7
commands:
  sleep:
    description: Accepts or denies a request to sleep.
    usage: /sleep [accept|deny]
  afk:
    description: Toggles AFK status for each player
    usage: /afk
  getafk:
    description: Gets AFK status for each player
    usage: /getafk
