name: MinewestCore
main: net.minewest.minewestcore.MinewestCorePlugin
authors: [Taon2, spencrr]
version: 1.0.8
commands:
  sleep:
    description: Accepts or denies a request to sleep.
    usage: /sleep [accept|deny]
