name: MinewestCore
main: net.minewest.minewestcore.MinewestCorePlugin
authors: [Taon2, spencrr]
version: 1.1.1
commands:
  sleep:
    description: Accepts or denies a request to sleep.
    usage: "Usage: /sleep [accept|deny]"
  afk:
    description: Toggles AFK status for each player
    usage: "Usage: /afk"
  getafk:
    description: Gets AFK status for each player
    usage: "Usage: /getafk"
